### ISSUE TITLE
Wrong fan mode

### ISSUE THREAD

**Issue by dukicn** [jcwillox/hass-template-climate#13]
Climate template is expecting wrong values for Fan mode. My fan modes are defined as:
fan_modes:
      - "auto"
      - "low"
      - "medium"
      - "high"
fan_mode_template: "{{ state_attr('sensor.term3', 'Fan') }}"

fan_mode_template shows a correct value in template editor. However the logs indicate that these are wrong values and it expects off, heat and cool:

[custom_components.climate_template.climate] Received invalid fan mode: High. Expected: ['off', 'cool', 'heat'].

set_fan_mode action does work and changes the fan mode as requested, but it doesn't show the requested value in the card. No matter which mode I press, it changes the mode on the device, but the change is not reflected in the card.

**Comment by jcwillox** [comment]
So this issue is two-fold, one is that the state must be lowercase so using the template `{{ state_attr('sensor.term3', 'Fan') | lower }}` should suffice. The other is a bug that I missed in #6, which is causing it to print the HVAC modes instead of the fan modes in that error message.

I've just published release [0.4.1](https://github.com/jcwillox/hass-template-climate/releases/tag/0.4.1) to fix that second issue.

**Comment by dukicn** [comment]
Thanks, works now.
